inherit: false
path: logs
defaultType: file
level: 3
methods:
    log:
        level: 2
        output: console
    access:
        level: 3
        output: access_log
    notice:
        level: 3
        output: trace_log
    warn:
        level: 4
        output: error_log
    error:
        level: 5
        output: error_log
outputs:
    console:
        type: stdout
        maxLength: 10000
    access_log:
        path: access.log
        maxLength: 10000
    trace_log:
        path: app.log
        maxLength: 10000
    error_log:
        path: app.log.wf
        maxLength: 10000
